### ISSUE TITLE
Mettre en place une documentation technique et fonctionnelle

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#191]
Rappel de la discussion en MP :

> > - faire une documentation technique (genre Javadoc ou Doxygen) ;
> > - Héberger cette documentation sur une page web (mise à jour à chaque push) ;
> 
> On en a déjà parlé avec WinXaito. Je trouve ça bien. Je n'ai juste pas encore trouvé la meilleure façon de le faire encore. J'aimerai un truc qui permet de rédiger une vrai doc pas uniquement technique comme le fait la javadoc, mais aussi fonctionnelle, etc. Un truc comme Readthedocs ([un exemple de doc](http://pop-java.readthedocs.io/en/latest/))

J'ai fait quelques recherches sur la question.

ReadTheDocs utilise [Sphinx](http://www.sphinx-doc.org/en/stable) (générateur de doc Python) pour générer la documentation : on peut donc intégrer aussi la doc technique sur ReadTheDocs*. Voir [un exemple de projet Java](https://github.com/nikolavp/approval/tree/master/doc) qui [utilise ReadTheDocs](http://approval.readthedocs.io/en/latest/javadoc/packages.html) pour la doc technique ET fonctionnelle, grâce à [JavaSphinx](http://bronto.github.io/javasphinx/) (une extension Sphinx).
- [x] créer [le projet sur ReadTheDocs](http://zest-writer.readthedocs.io) ;
- [x] créer les fichiers de docs fonctionnelle en se basant sur le readme ;
- [x] mettre en place la génération de la doc technique ;
- [x] dire à RtD d'utiliser mon fork. cf. [ça](http://docs.readthedocs.io/en/latest/yaml-config.html#conda) et [ça](http://docs.readthedocs.io/en/latest/conda.html) et [ça](http://stackoverflow.com/questions/19042389/conda-installing-upgrading-directly-from-github).

**TODO Javalang / Javasphinx**
- redéfinir la toc de la javadoc (modif [ici](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/apidoc.py#L58)) ;
- ajouter une option générer des TODOs dans la javadoc rst à partir des tags `@todo` (modif [ici](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/compiler.py#L92)) :

```
tree = javalang.javadoc.parse(" /** This class is a test\n @param foo The foo value\n@todo Faire ceci\n@todo et cela*/ ")
tree.tags
> {'todo': ['Faire ceci', 'et cela'], 'param': ['foo The foo value']}
```
- ajouter une option pour inclure les [graphes de dépendances](http://www.sphinx-doc.org/en/stable/ext/graphviz.html#module-sphinx.ext.graphviz) à la Javadoc (modif [ici](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/compiler.py#L92)) ;
- ajouter une option pour [la couverture de doc](`sphinx.ext.coverage`) (modif [ici](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/compiler.py#L65));

-> Pour récupérer une option CLI : passer l'option en param [ici](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/apidoc.py#L314) et [là](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/apidoc.py#L204) (ou bien pass `opts` en arg).
-> pour ajouter une directive reST, cf [ici](https://github.com/bronto/javasphinx/blob/53e2916847bd4ddf6302c467fde3aa7ca8df08c2/javasphinx/apidoc.py#L62) :

```
toc = util.Directive('toctree')
toc.add_option('maxdepth', '2')
doc.add_object(toc)
```

-> [langage DOT](http://graphviz.org/content/dot-language) (graphviz) :

```
echo "graph {a[shape=square, color=blue, label="Bonjour"] a--b c--d--e[color=blue] a--c  a--e}" | circo -Tpng > hello.png
```

**TODO divers**
- checker [conf.py doc](http://www.sphinx-doc.org/en/stable/config.html) et l'ajouter dans la doc, virer tout ce qui est inutile ;
- voir comment dire à rtd de ne pas remplacer la version et de laisser la date ;
- mettre à jour le fichier requierements.txt quand mes PRs sur Javasphinx seront mergées.
- je ne suis pas sensé appeler javasphinx-apidoc

---

**javasphinx installation from source**

```
cd zest-writer
git clone https://github.com/roipoussiere/javasphinx.git
mv javasphinx/javasphinx doc
rm -rf javasphinx
pyvenv doc/venv
source doc/venv/bin/activate
python --version # check it's 3.4
pip install -r javasphinx_requ # see javasphinx_requ
gradle doc
```

---

**javasphinx_requ**

```
Babel==2.3.4
Jinja2==2.8
MarkupSafe==0.23
Pygments==2.1.3
Sphinx==1.4.6
alabaster==0.7.9
beautifulsoup4==4.5.1
docutils==0.12
future==0.15.2
imagesize==0.7.1
javalang==0.10.0
lxml==3.6.4
pytz==2016.6.1
six==1.10.0
snowballstemmer==1.2.1
sphinx-rtd-theme==0.1.9
```

**Comment by WinXaito** [comment]
Ça en est où ici ?

**Comment by lypwig** [comment]
J'attendais un peu vos retours avant d'aller plus loin.

Sinon cet après-midi je me mets au code, je vais pouvoir avancer sur pas mal de tickets auxquels je me suis affecté.

**Comment by WinXaito** [comment]
Nice ;)

**Comment by firm1** [comment]
Hourra

Le sam. 9 juil. 2016 15:57, Kevin Vuilleumier notifications@github.com a
écrit :

**Comment by lypwig** [comment]
Bon pas trop eu le temps ce week-end, je m'y met cette semaine (au moins Jeudi c'est férié :-P).

**Comment by firm1** [comment]
Juste pour dire, que ce que tu propose là haut me convient bien. Et n'hésite pas si tu as besoin qu'on te soulages sur certaines issues attribuées.

**Comment by firm1** [comment]
> je peux vous ajouter en mainteneurs, il me faut juste vos pseudos rtd

"firm1" pour ma part.

**Comment by WinXaito** [comment]
`WinXaito` pour moi :p

**Comment by lypwig** [comment]
Bon, j'arrivais pas trop à avoir générer la doc pour readthedocs, du coup là j'ai généré la Javadoc et poussé sur la branche gh-pages, du coup ça fait une doc technique en ligne : https://roipoussiere.github.io/zest-writer/

Mais ça ne me convient pas trop, je vais persévérer avec javasphinx l'avoir sur readthedocs.

**Comment by firm1** [comment]
Vive la persévérance !!!

**Comment by lypwig** [comment]
Je vais me coucher mais j'ai bien avancé sur ce point, je pense être capable de mettre en ligne un truc demain.

Question : pourquoi dans le code il y a des interfaces avec du contenu dedans (et le mot-clé default devant) ? JavaSphinx n'aime pas du tout. -> Est-ce que c'est vraiment utile / Peut-on faire autrement ?

**Comment by WinXaito** [comment]
Wut je suis sur que sa se trouve dans les plugins. Si je ne dit pas de bêtise, le mot clé `default` est nouveau dans java8. Il permet de ne pas rendre la définition de la fonction obligatoire.

**Comment by lypwig** [comment]
> Wut je suis sur que sa se trouve dans les plugins.

[Un ticket](https://github.com/bronto/javasphinx/issues/42#issuecomment-248837065) est dessus. En attendant, je supprime le contenu des interfaces pour générer la doc. Si c'est pas trop compliqué d'éviter les `default` et les corps d'interface, ce serait bien de modifier, sinon on attends le correctif.

**Comment by firm1** [comment]
> Question : pourquoi dans le code il y a des interfaces avec du contenu dedans (et le mot-clé default devant) ? 

Comme l'a mentionné @WinXaito c'est une feature de java8 qui permet d'éviter de dupliquer du code dans les classes qui appellent l'interface.

En soit tu peux ignorer les interface dans javasphinx pour l'instant. C'est mieux que de créer des doublons dans le code je pense.

**Comment by lypwig** [comment]
> En soit tu peux ignorer les interface dans javasphinx pour l'instant. C'est mieux que de créer des doublons dans le code je pense.

Je ne peux pas, pour générer la doc javasphinx parse tout le code et me jette au 1er truc louche venu. Donc ce que je fais là c'est supprimer les `default` et le contenu des interfaces juste pour générer la doc, mais ça ne peut être que temporaire car vous ne pourrez pas builder la doc de votre coté.

**Comment by firm1** [comment]
ok

**Comment by WinXaito** [comment]
Y a pas d'update java8 pour javasphinx ?

**Comment by lypwig** [comment]
Je ne crois pas, ou alors c'est pas encore très bien intégré.

Je suis le ticket en tout cas.

**Comment by lypwig** [comment]
Un petit avant goût : http://zest-writer.readthedocs.io/fr/doc/

Il y a encore des petits trucs à faire :
- étoffer un peu les pages de doc ;
- les taper un .rst et pas en .md car ReadTheDocs n’interprète pas la syntaxe (cf. page installation), ou alors tenter de mieux configurer RTD ;
- build automatique de la doc au push sur ZW/master ;
- mieux configurer ReadTheDocs et le fichier de config sphinx (divers, notamment zest-writer.readthedocs.io/ est 404) ;
- avoir 2 docs, une stable et une latest ;

... ce qui ne me pose pas de soucis, c'est juste que j'ai pas eu le temps ce soir.
